### ISSUE TITLE
Manual installation documentation

### ISSUE THREAD

**Issue by ghost** [ericpaulbishop/redmine_git_hosting#8] opened 2011-05-13 04:31 UTC
I tried installing this about 4 times, and failed each time. The configuration instructions on the Readme is really confusing, and there's no step by step instructions. I don't mind installing this manually, even if it takes a little work, but I need to know what to do. :( This project looks really great too.

I'd really appreciate it!

**Comment by kyse** [comment] 2011-05-13 13:43
Yes, I agree, I could use some more details on the installation as well.  I have gitolite installed with the dev redmine trunk I got everything installed, and can get to the point where I can create a new database, everything works out ok, says project created, however when I goto repository, it still says repository is empty, and (git)~/repository/  doesn't have the repository created in it.  So I'm assuming my issues is with the ssh keys.  I created the key's as you're instructions.  However, you said place the second key (which I'm assuming is the user key) outside of the gitolute generated section of (git)~/.ssh/authorized_keys file.  So with that all taken care of I'm left with one conclusion.  The admin key needs to be placed inside the gitolite section of the authorized_keys file for the git account.  So I added the admin key to the gitolite-admin/keydir/ directory and added the permissions in the config file to let the gitolite_admin_id_rsa user to read and write to the gitolite-admin repo.  Why are we not including the user_id_rsa file inside the gitolite controlled part of authorized_keys file for git?  Won't that prevent the user_id from being assigned to gitolite repo's?  Anyways, I entered the git_user_id_rsa.pub line into the authorized_keys file outside of the gitolite section as instructed.

Just an update this morning after doing some testing though, I did check and noticed in the gitolite config file, after I created the new project, the new repo appears in the gitolite.conf file, so why is the empty init of the repo failing?  I notice there's no read/write username access line under the repo name.  It appears this is why an empty repo isn't being initialized and created.  So now I here I am, unsure of how to proceed.

Thanks.

**Comment by kyse** [comment] 2011-05-13 17:09
Just a followup, if I add a ssh key via the plugin for my redmine user then the second line of the repo (in gitolite-admin/conf/gitolite.conf file) appears, and the empty git repo is initialized correctly.  I still can't get the repository under the project to show correctly though.

**Comment by kyse** [comment] 2011-05-14 15:06
So I was doing some debugging, and noticed when it tries having www-data connect to git@servername, it was failing because it couldn't edit the www-data home of /var/www to create .ssh/known_hosts file because this directory was owned by root.  Just mkdir /var/www/.ssh, chown -R www-data:www-data .ssh to solve this.  Just a heads up to anyone else having issues.  Once I did this, i was able to successfully manually perform a "ssh -o BatchMode=yes -o StrictHostKeyChecking=no -i ~/.ssh/git_user_id_rsa git@servername.com"  which is what the code is trying to do.

**Comment by kyse** [comment] 2011-05-15 18:15
Damn, I'm dieing here, I can't figure this out.  the plugin will handle the permissions and keys perfectly, but when i create a new project, no repo is creatd in /var/lib/gitolite/repositories.  And if I manually create it, init it, and push an innitial commit to it, I still can't get the repository to show up under the repositories tab.  i do see in var/www/redmine/logs still says the repository isn't created and just shows the instructions when infact the repo is created.  How come it wont show.  I've tested logging in with www-data to git using the user key and it logs into git account find, and I know the admin key works fine because it will add the repo to the gitolite-admin conf file fine.

Please throw me some hints.

**Comment by ghost** [comment] 2011-05-15 23:14
Well, the Yourchili bash library installs it for you, so technically you can see how it does it.
But this is definitely not the easiest way to figure it out, which is why I need some real documentation. Hopefully it'll help you out some though.

https://github.com/ericpaulbishop/yourchili

**Comment by kyse** [comment] 2011-05-16 21:53
Yea, didn't help.  Still can't debug what's wrong.

**Comment by bishopandco** [comment] 2011-05-21 21:39
kyse, make sure you do not have duplicate keys in your git users authorized_keys and also make sure you generate NEW KEYS for the users that you want to be able to clone from. I am working on some docs that I hope will clarify.

**Comment by ghost** [comment] 2011-05-21 21:40
Appreciate it. :)

**Comment by perryk** [comment] 2011-05-23 23:02
I am having similar problems as Kyse, Redmine always says "Repository does not exist.". The gitolite key looks ok and the gitolite config updates upon new projects + users etc. I'm able to clone and push to gitolite repos fine as users who have keys uploaded into Redmine. The git_user key should be ok also as I am able to do the following without a password:
sudo -u www-data ssh -o BatchMode=yes -o StrictHostKeyChecking=no -i ~www-data/.ssh/git_user_id_rsa git@server

I have taken a look git.sh from yourchili but don't seem to be able see where it copies the private keys to /var/www/.ssh so maybe something else I am missing from there ?.

Any ideas on anything else I can do to troubleshoot the process by which Redmine is determining if it can display/read the repository ?

Thanks.

**Comment by EspadaV8** [comment] 2011-05-25 03:17
I am so lost with this.

I tried to install it as a plugin to redmine but that got nowhere with the error

undefined method `sq_bin' for class`Class'

Since I was planning on switching to ChiliProject anyway I installed a temp set up of that in my home folder and have managed to get the plugin to register, however, I'm not getting anything added to the gitolite-admin repo (and thus no repos created).

Checking the log I'm seeing things like...

bad command: git "--git-dir" "repositories/aa.git/" "branch" "--no-color" 
bad command: git "--git-dir" "repositories/aa.git/" "ls-tree" "-l" "HEAD:" 

I'm assuming that this is because the folders there don't exist.

I was also getting the error;

Failed to add the host to the list of known hosts (/var/www/.ssh/known_hosts).

Because the folder didn't exist. Creating that folder and chown-ing it to www-data allows the host to be saved, but nothing actually gets done with the repos or the gitolite config files.

Any advice on what might be going on? (I'm unsure if the the user is connecting but can't edit things or if it's not even connecting or it is connecting but trying to edit the wrong things).

Thanks

**Comment by ghost** [comment] 2011-05-25 03:44
The undefined method sqbin error you're getting is because you're using Redmine 1.1.x (or older). The error doesn't occur on 1.2.x (or trunk if 1.2 isn't out yet). In another thread, the plugin author said he wasn't going to fix the issue since 1.2 is so close. Just upgrade and the error will go away.

Also, on 1.2 there's a new option for Git repositories called "Report last commit for files and directories" (in the repositories tab in the settings for a project). If this is unselected, in the repository view, only the files and size will be reported as information, and the revision, age, comment, and author extra information will be omitted. If you ever see this "problem" happen to you, just select that option and it'll appear back. Hopefully that'll save you from the trouble I had figuring out what in the world happened in the repository view.

**Comment by that0n3guy** [comment] 2011-06-02 18:28
I basically followed lines 25 through 123 on this: https://github.com/ericpaulbishop/yourchili/blob/master/library/git.sh

Then I created a subdomain in my dns to git.mysite.com to point at my server IP and added at url to the plugin setting in the 2 spots (http and domain).

My ssh git urls work great, the http urls do not.  Not sure how to get them working so I just disabled them for now.

**Comment by EspadaV8** [comment] 2011-06-03 01:47
@Roejames12 - Redmine has been updated to 1.2 now so I shall have a check on there too at some point. Since I have CP already working as a copy of the site I'll carry hacking through that. Thanks for the info, I'll see if that happens.

@that0n3guy - I have a git user set up and git/gitolite is working outside of RM/CP and I can git clone on my local machine, the problem only seems to be with the users being used by CP.

I've not had any time to look into it since my last comment. What would be helpful is a way to debug what's happening step by step.

It looks like some connections are happening and working. The git clone isn't denied other than the fact that the folder doesn't exist, which I think is caused by something else not working with editing/cloning the gitolite repo.

**Comment by that0n3guy** [comment] 2011-06-03 02:34
@espadaV8.  I had a working copy of CP running already too.  All I really did is go through those line in the git.sh manually in the terminal and rebooted and everything is working w/ my CP users.

Try git cloning using the url given by CP before you try creating and pushing to from local to the server.  Seems like I couldn't push anything until I got my first git clone to finally work.

**Comment by ohthehugemanatee** [comment] 2011-07-11 08:26
I walked through the setup script, and everything works well except for:
- automatic repo creation.  It doesn't happen, and I can't find any errors in chiliproject's logfile to chase this down.  Not a big deal for me, but it's weird.
- adding chiliproject users to git's authorized_keys file.  It worked at one point, but apparently I borked it since then.  

I've confirmed that apache has access to git by running 

sudo -u apache ssh -o BatchMode=yes -o StrictHostKeyChecking=no -i ~apache/.ssh/git_user_id_rsa git@servername.com

sudo -u apache ssh -o BatchMode=yes -o StrictHostKeyChecking=no -i ~apache/.ssh/git_admin_id_rsa git@servername.com

I've modified git's authorized_keys, so both keys get full access. So with both keys, I get a bash prompt.

So when the repo is there, Chiliproject has no problem seeing and interacting with the repo.  But it can't create the repo, and it can't add users' keys to authorized_keys or gitolite.conf .  I'm not sure where to go from here to troubleshoot.  Advice?

**Comment by that0n3guy** [comment] 2011-07-11 17:18
Yeah he modified the script so now its missing a part for manual install, you also need to do lines 83-87 on: 
https://github.com/ericpaulbishop/yourchili/blob/ff744ed19e052e9b68a04c449a2e77fc97710c89/library/git.sh

**Comment by ericpaulbishop** [comment] 2011-07-11 18:36
I updated the documentation for the new sudo implementation, which now has step-by-step instructions.

**Closed as completed by ericpaulbishop** 2011-07-11 18:36 UTC

**Comment by bishopandco** [comment] 2011-07-12 03:44
Beat me to it. Nice work!

**Comment by ohthehugemanatee** [comment] 2011-07-12 11:07
Still having trouble, but I don't think it's related.  Basically I can get the plugin to create repos and add/remove users, but Redmine's Repository tab still insists that there's no repo there.  The scripts in /tmp are being used for everything I can see in the debug log, and they work fine for me as the Apache user.  Tracking it in https://github.com/ericpaulbishop/redmine_git_hosting/issues/27 .

**Comment by ghost** [comment] 2011-09-09 04:08
Thanks for the documentation. I was able to get everything created and working 100% with your instructions (minus the bugs I had reported earlier). :)
