### ISSUE TITLE
gitolite multi/e-mail keys not supported

### ISSUE THREAD

**Issue by juselius** [ericpaulbishop/redmine_git_hosting#77] opened 2011-09-06 12:25 UTC
Under gitolite a single userid can have multiple keys associated with it: The user jonas could add two keys, named jonas@foo.pub and jonas@bar.pub, while gitolite.conf would read

repo foobar
   RW+ = jonas

gitolite distinguishes between the situation where the userid is an email address, and  handles the situation correctly. A problem arises under redmine when a user has registered with an email address as the user name, because the git_hosting plugin mangles the name (. -> _) so that gitolite does not properly recognize the id as an email key. 
Furthermore, if a user adds more than one key, the keys should really be tagged with @1, @2 so that they become proper multikeys. This would also reduce clutter in gitolite.conf, since each userid would only have to be added once to a repo, instead of once for each key.

**Comment by ericpaulbishop** [comment] 2011-09-06 15:39
It is true that this plugin does not take into account the full range of features available in gitolite in naming users, but this is not a bug, this is a feature request.  The model the plugin currently uses is merely more simple than what can be used in gitolite.

I may get around to this feature request at some point but it is not even close to a high priority, so I'm closing this issue.  

If you want to implement this, of course, go right ahead. Patches welcome :-)

**Closed as completed by ericpaulbishop** 2011-09-06 15:39 UTC

**Comment by juselius** [comment] 2011-09-07 08:00
I'll consider creating a patch for this, but I'm not much of a Ruby/Rails programmer (yet): My secret wish upon a falling star is that Redmine would be written in Django, hahahahaha ;)

I have some questions regarding they keys. I don't quite understand what the need is for such an elaborate scheme to "ensure" unique names for keys. I suspect that in most setups redmine is fully in charge of the gitolite repositories, i.e. there are no, or very few external users in the gitolite setup. The risk of a name clash is thus very small. Since user names are already unique under redmine, the corresponding keys  could simply be named userid@n.pub, where n is an integer which is incremented every time a user adds a key (and never decremented!). If user uniqueness is required, one could simply create a single random integer for each user, so that the gitolite user would be e.g. snafu_18238782923@1. 

Or did I miss something critical? Jonas
