### ISSUE TITLE
undefined method `sq_bin' for class `Class'

### ISSUE THREAD

**Issue by fbrier** [ericpaulbishop/redmine_git_hosting#3] opened 2011-05-03 01:04 UTC
I checked the redmine_git_hosting plugin out into my vendor/plugins directory.  Git is installed as well as the 3 gems documented in the project page.  Redmine fails to start.  When I ran the command:

rake db:migrate:plugins RAILS_ENV=production

I received the error message:

undefined method `sq_bin' for class`Class'

sq_bin appears to be a function defined in the Redmine git adapter, but I thought it was included as part of all the scm adapters.  Perhaps I am missing a gem?  Thank you for any assistance.

**Comment by TGM** [comment] 2011-05-05 19:54
I can confirm this.
Appears when trying to migrate to database.

sudo -u www-data X_DEBIAN_SITEID=default RAILS_ENV=production rake db:migrate:plugins

**Comment by nkulikov** [comment] 2011-05-06 05:15
I've tried to replace redmine (v1.1.3) git adapter file with the same from chiliproject. It helps to avoid this issue, but there will be one more with other class from redmine, so I've decided to switch on ChiliProject.

**Comment by thimios** [comment] 2011-05-06 13:46
It would be really great if the plugin would continue work on Redmine as well and not only ChiliProject. Is there a chance to fix this? Thanks!

**Comment by TheEmpty** [comment] 2011-05-06 15:37
yes I was looking forward to using this, I don't think I would go through the pain of migrating my issues and users to Chili just for this though, I still haven't seen what it can do!

edit: can anyone tell me what rev. is currently working with redmine (trunk)?

**Comment by TheEmpty** [comment] 2011-05-06 16:52
sq_bin is called here:
https://github.com/ericpaulbishop/redmine_git_hosting/blob/5947b98502b5b4eac1ab5ae655be06c418cb266c/lib/git_hosting/patches/git_adapter_patch.rb#L15
https://github.com/ericpaulbishop/redmine_git_hosting/blob/5947b98502b5b4eac1ab5ae655be06c418cb266c/lib/git_hosting/patches/git_adapter_patch.rb#L28

**Comment by ericpaulbishop** [comment] 2011-05-06 20:11
This issue does not occur if you use Redmine trunk, instead of the 1.1 branch.  When they create the 1.2 branch (which is now 6 days orverdue), this error won't occur, and the plugin will be fully supported.

Since as soon as the 1.2 branch gets released this problem is just going to go away, I don't feel that it's worth my time to come up with a fix for older versions.  However, if someone wants to work on this and send me a pull request, I'll gladly incorporate it.

**Comment by TGM** [comment] 2011-05-06 20:34
Well that explains it, i used "apt-get install redmine-mysql redmine libapache2-mod-passenger" to get readmine up and running.

**Comment by TheEmpty** [comment] 2011-05-08 01:59
(For any future reference, I got my servers mixed up and the one that I thought was trunk was not)

**Comment by fbrier** [comment] 2011-05-11 22:20
I can wait for 1.2.  Thank you very much for the plugin.  I am looking forward to trying it out.

**Comment by ghost** [comment] 2011-05-12 10:56
Arg, this plugin looked so great.. Then I hit this. :(

**Comment by TheEmpty** [comment] 2011-05-12 17:35
@Roejames12 well the new release should be coming soon and I would recommend using their trunk or master branch instead of stable. You get the ability to have private issues, delete users, etc.

**Comment by ericpaulbishop** [comment] 2011-05-13 21:03
I'm just going to close this issue since I have no intention of addressing this myself (as noted above).  If anyone wants to fork/send a pull request please do and I'll gladly merge it.

**Closed as completed by ericpaulbishop** 2011-05-13 21:03 UTC
