### ISSUE TITLE
The repositories are not displayed

### ISSUE THREAD

**Issue by voondo** [ericpaulbishop/redmine_git_hosting#15] opened 2011-06-06 12:06 UTC
Everything seems to be well configured because gitolite-admin is correctly updated and repositories are automatically added in gitolite.
But when I go to the Repository tab I always have : "Repository does not exist. Create one using the instructions below."
When I follow the given commands : 
mkdir sandbox
cd sandbox
git init
touch readme.txt
git add readme.txt
git commit -m 'Initializing Sandbox repository'
git remote add origin git@[MYSERVER]:sandbox.git
git push origin master

It works like a charm but I always have the message : "Repository does not exist."

What's going on ? How may I find useful debug informations ?

edit: I use redmine 1.2
edit: I guess I found where the problem comes from. In redmine logs I have : 
Shelling out: '/tmp/redmine_git_hosting/run_git_as_git_user' --version --no-color
Shelling out: 'git' '--git-dir' 'repositories/bac-a-sable.git' '-c' 'core.quotepath=false' '-c' 'log.decorate=no' 'branch' '--no-color'

It means, if I correctly understood, that the second command is executed locally instead of being executed through ssh (sq_bin_with_ssh is not called). So it's logical that it doesn't find anything. But why it uses 'git' instead of '/tmp/redmine_git_hosting/run_git_as_git_user' ?

**Comment by perryk** [comment] 2011-06-08 00:04
This looks like the same problem I am having also. Redmine 1.2, everything working ok from the commandline, but Redmine always says Repository does not exist. I am happy to test anything if anyone has ideas for debugging or a fix.

**Comment by voondo** [comment] 2011-06-08 11:48
I think there is a problem with "alias_method_chain :sq_bin, :ssh" in lib/git_hosting/patches/git_adapter_patch.rb because sq_bin_with_ssh is not always called. But why...?
Ruby hackers, please, help us :)

**Comment by that0n3guy** [comment] 2011-06-08 15:11
Perryk, are you saying that after you "git push" your command line says "repository does not exist"?  or are you saying that your CP repository page stills says it doesn't exist?

Also, is it a "sub" project?  If so, it might be because of #12 and #16.

**Comment by perryk** [comment] 2011-06-09 01:57
Hi, "git clone" and "git push" from a command line work fine for a user who has uploaded a key into Redmine. It is on the Redmine webpage at the Repositories Tab for the project that is always displays "Repository does not exist." then gives the instructions for creating a empty repo and pushing it up to the server.  It is not a sub project.

**Comment by that0n3guy** [comment] 2011-06-09 14:26
Hmmm, I have no idea.  You sure your settings in for the plugin specify the repository directory? (probably does, but I thought I'd ask).

**Comment by perryk** [comment] 2011-06-09 22:12
Yep, the "Git Repository Base Path (Relative to git user home)" setting I have left as the default of "repositories/". The actual repos live in "/home/git/repositories" so all should be good. Cheers for making suggestions, I am happy to take a closer look at anything.

**Comment by cocinerox** [comment] 2011-06-13 02:09
Hey, any news on this? I have exactly the same issue (on CP 2.0.0 RC1&RC2), and it's exhausting...

**Comment by cocinerox** [comment] 2011-06-18 15:08
Solution proposal: in the 'repositories' mysql table the 'url' and 'root_url' fields have to contain the FULL path to the repositories, not just 'repositories/xyz.git' (which is done in "lib/git_hosting/patches/projects_controller_patch.rb" line 20). This way after the first commit the Repository tab works well. Hope that helps and can be fixed in the code. Cheers

**Comment by ericpaulbishop** [comment] 2011-06-18 21:09
I think the problem may be that you haven't set gitRepositoryBasePath -- this is the base path to your git repositories, e.g. /home/git/repositories/.  I've updated the default to /home/git/repositories, but this really is something that should be set manually.

**Comment by voondo** [comment] 2011-06-19 10:29
As suggested by cocinerox, my 'url' and 'root_url' now contain the full path to the repositories. But it doesn't help...

ericlpaulbishop : my gitRepositoryBasePath was "repositories/" which is "relative to git user home" (as indicated in the form). I tried to set the absolute path '/var/lib/gitolite/repositories'  but it doesn't help either.

But in logs I don't understand why I get : 
Shelling out: 'git' '--git-dir' '/var/lib/gitolite/repositories/sandbox.git' '-c' 'core.quotepath=false' '-c' 'log.decorate=no' 'branch' '--no-color'
It should be : '/tmp/redmine_git_hosting/run_git_as_git_user' instead of 'git', isn't it ?

edit : the problem comes from that : my 'redmine' user (who runs the ruby process) doesn't have read access to the git home therefore the git command without ' /tmp/redmine_git_hosting/run_git_as_git_user'  fails.

example : 
redmine $ 'git' '--git-dir' '/var/lib/gitolite/sandbox.git' '-c' 'core.quotepath=false' '-c' 'log.decorate=no' 'branch' '--no-color'
fatal: Not a git repository: '/var/lib/gitolite/repositories/sandbox.git'

redmine $ '/tmp/redmine_git_hosting/run_git_as_git_user' '--git-dir' 'repositories/sandbox.git' '-c' 'core.quotepath=false' '-c' 'log.decorate=no' 'branch' '--no-color'
- master

Q.E.D

**Comment by mtippmann** [comment] 2011-06-19 15:33
I have the same issue. I fixed the permissions so that even if git is not run over ssh it can read the repo, however I still have no repository view nor can I view files in a repository. 

edit: I had to run rake tmp:clear and restart apache to show the repository. So the problem is the git adapter.. It appears the code is in question is in redmine_git_hosting/lib/git_hosting/patches/git_adapter_patch.rb

gitolite is working fine, redmine is 1.2, debian 6.0

**Comment by voondo** [comment] 2011-06-24 11:09
The problem comes from redmine itself in 'redmine/scm/adapters/git_adapter' : scm_cmd directly uses the constant GIT_BIN instead of self.class.sq_bin. (maybe it should be reported to redmine devs ?)
The workaround solution : in config/configuration.yml put :
default:
  scm_git_command: /tmp/redmine_git_hosting/run_git_as_git_user

And as glycoknob said : rake tmp:clear and restart redmine

**Comment by marlyx** [comment] 2011-06-28 14:33
I have the same issue with ChiliProject 2.0RC3, and I think I have figured out what the actual problem is.

When the **redmine_git_hosting** plugin saves the the path to the repository In the **Redmine/ChiliProject** database, it is saved as a relative path to the git home (e.g. repositories/myrepo.git). This becomes a problem since the git viewer built into Redmine/Chiliproject have it's PWD set to the home of the user running the web service (ie. redmine or chiliproject, ..), thus making the relative paths to the repositories invalid, and making redmine/chili really unhappy.

Quickfixes for this:
1) Use the fix stated by voondo above. This will route every call to view the git repo trough SSH, which is dog-slow.

2) Create a tiny wrapper script around git, that will change directory to the home of the git user. And then set the scm_git_command: pointing to it in your configuration. (this is what I did, and it works quite nice).

Longterm though, this have to fixed in some other way, either here or in Redmine/ChiliProject.

**Comment by ericpaulbishop** [comment] 2011-06-28 15:22
martande -- the goal is to make every call to get go though SSH as in your suggestion (1).  You are absolutely correct that this is slow as sh*t.  I actually hadn't initially realized that redmine/chiliproject isn't doing any caching of the git commits (I had naively thoought that the fetch_changesets functionality was doing this, but I didn't look closely enough...), so this is even slower than I anticipated.  The real solution is to implement some sort of caching.

This solution really is NOT designed for high-traffic sites right now.  It needs to be re-worked and optimized for that.  Right now it's mostly a tool I use to manage my own personal, private git repos.  I may further optimize, but there are a lot of other things that are a much higher priority for me right now.

Now the real question with this issue is why GIT_BIN is being called instead of sq_bin in some cases, which is why the initial implementation would fail to work at all (as described by others above).  I really need to get a chance to look at the latest chiliproject/redmine code and see why it might not be working. I haven't been able to replicate the problem on chiliproject 1.4.  I may need to update the git adapter patch to deal with this issue.

**Comment by ericpaulbishop** [comment] 2011-06-28 21:18
I think I (finally) figured out what's going on here.  Redmine 1.2 and ChiliProject 2.0RC changed the git_adapter code so that other methods need to be patched too.  ChiliProject 1.x (which is what I was using) worked fine, so I didn't see the issue.

For those of you having trouble with this, try it again now.

**Comment by perryk** [comment] 2011-06-29 05:24
This is working for me now, awesome! Thanks.

I tried Voondo's suggestion yesterday and that worked. Today I have tried with the latest git_adapter_patch commit and things look to be working ok with that fix also.

I'm a little confused about if I am meant to be seeing "/tmp/redmine_git_hosting/run_git_as_git_user" as the git command in the Enabled SCMs though (an Administration/Settings/Repositories). Is this being set by the plugin ? What happens for example if I want to try a different wrapper like Martande did in his option 2 ?

**Comment by marlyx** [comment] 2011-06-29 13:40
erikpaulbishop - 
After the latest commit it workes as it should, all by it self. Thanks.

I have a solution to the "slow as s**t" problem :). If the scripts that tunnels trough SSH used the Master / Slave connection functionality of SSH, only the first ever connection to the git host will be slow, all consecutive connects will be nearly as fast as local git.

I have tried to enable this in the helper scripts (**run_git_as_git.sh** etc.) on my box, and it work really well, just as fast as local git, but with just one little snag. On the first connect to the git server the master connection have to be made and forked into the background (this one should live forever). The problem is that the **shellout()** function in redmine/chili will block and wait for **ALL** subprocesses created, thus waiting forever for the master SSH process to finish. :(

This is the script I used:

```
cmd=$(printf "\"%s\" " "$@")
if [ "$USER" = "git" ] ; then
  cd ~
  eval "git $cmd"
else
  if [ ! -S "${master_socket}" ]; then
    ssh -M -S ${master_socket} -i ${identity} -o BatchMode=yes -o StrictHostKeyChecking=no ${target} -f -N -n  
  fi
  exec ssh -S ${master_socket} -o BatchMode=yes -o StrictHostKeyChecking=no ${target} "git $cmd"
fi
```

As I said above this works really sweet when the master connection is already made (manually), but chokes when Redmine/Chili tries to create it, since a child process is created and it will be waited upon until the end of days. Maybe some more patching of the git_adaptor / abstract_adaptor can fix this?

**Comment by ericpaulbishop** [comment] 2011-06-29 14:35
I'm closing this issue, since the source of this problem seems to be fixed now.

martande: I've actually been thinking about how to speed things up a bit, and I think the best way may be to not use SSH at all for running git, but rather sudo.  I was looking at the sudo docs and there's a way to edit the sudoers file to let one user run code as another user, and only that user (e.g. no super-user escalation priviledges, or any other users priviledges), without entering a password.  Editing sudoers may actually be easier than setting up a second ssh key too.

**Closed as completed by ericpaulbishop** 2011-06-29 14:35 UTC
