### ISSUE TITLE
Issue in migration with redmine 1.2.1

### ISSUE THREAD

**Issue by omkar-khutare** [ericpaulbishop/redmine_git_hosting#40] opened 2011-07-19 15:21 UTC
I've updated redmine 1.2.1 . Now want to migrate redmine_git_hosting. I also done  the steps for migration as per the documentation. But whenever i am running migration task i.e RAILS_ENV=production rake db:migrate_plugins it gives me following error :
...........................................................
no such file to load -- open-uri-cached
/opt/ruby-enterprise-1.8.7-2011.03/lib/ruby/site_ruby/1.8/rubygems/custom_require.rb:31:in `gem_original_require'
/opt/ruby-enterprise-1.8.7-2011.03/lib/ruby/site_ruby/1.8/rubygems/custom_require.rb:31:in`require'
/opt/ruby-enterprise-1.8.7-2011.03/lib/ruby/gems/1.8/gems/activesupport-2.3.11/lib/active_support/dependencies.rb:184:in `require'
/opt/ruby-enterprise-1.8.7-2011.03/lib/ruby/gems/1.8/gems/rails-2.3.11/lib/rails/gem_dependency.rb:217:in`load'
/opt/ruby-enterprise-1.8.7-2011.03/lib/ruby/gems/1.8/gems/rails-2.3.11/lib/initializer.rb:307:in `load_gems'
/opt/ruby-enterprise-1.8.7-2011.03/lib/ruby/gems/1.8/gems/rails-2.3.11/lib/initializer.rb:307:in`each'
/opt/ruby-enterprise-1.8.7-2011.03/lib/ruby/gems/1.8/gems/rails-2.3.11/lib/initializer.rb:307:in `load_gems'
/opt/ruby-enterprise-1.8.7-2011.03/lib/ruby/gems/1.8/gems/rails-2.3.11/lib/initializer.rb:164:in`process'
/opt/ruby-enterprise-1.8.7-2011.03/lib/ruby/gems/1.8/gems/rails-2.3.11/lib/initializer.rb:113:in `send'
/opt/ruby-enterprise-1.8.7-2011.03/lib/ruby/gems/1.8/gems/rails-2.3.11/lib/initializer.rb:113:in`run'
/home/ubuntu/sites/redmine/releases/20110715095306/config/environment.rb:20
/opt/ruby-enterprise-1.8.7-2011.03/lib/ruby/site_ruby/1.8/rubygems/custom_require.rb:31:in `gem_original_require'
/opt/ruby-enterprise-1.8.7-2011.03/lib/ruby/site_ruby/1.8/rubygems/custom_require.rb:31:in`require'
/opt/ruby-enterprise-1.8.7-2011.03/lib/ruby/gems/1.8/gems/activesupport-2.3.11/lib/active_support/dependencies.rb:182:in `require'
/opt/ruby-enterprise-1.8.7-2011.03/lib/ruby/gems/1.8/gems/activesupport-2.3.11/lib/active_support/dependencies.rb:547:in`new_constants_in'
/opt/ruby-enterprise-1.8.7-2011.03/lib/ruby/gems/1.8/gems/activesupport-2.3.11/lib/active_support/dependencies.rb:182:in `require'
/opt/ruby-enterprise-1.8.7-2011.03/lib/ruby/gems/1.8/gems/rails-2.3.11/lib/tasks/misc.rake:4
/opt/ruby-enterprise-1.8.7-2011.03/lib/ruby/gems/1.8/gems/rake-0.9.2/lib/rake/task.rb:205:in`call'
/opt/ruby-enterprise-1.8.7-2011.03/lib/ruby/gems/1.8/gems/rake-0.9.2/lib/rake/task.rb:205:in `execute'
/opt/ruby-enterprise-1.8.7-2011.03/lib/ruby/gems/1.8/gems/rake-0.9.2/lib/rake/task.rb:200:in`each'
/opt/ruby-enterprise-1.8.7-2011.03/lib/ruby/gems/1.8/gems/rake-0.9.2/lib/rake/task.rb:200:in `execute'
/opt/ruby-enterprise-1.8.7-2011.03/lib/ruby/gems/1.8/gems/rake-0.9.2/lib/rake/task.rb:158:in`invoke_with_call_chain'
/opt/ruby-enterprise-1.8.7-2011.03/lib/ruby/1.8/monitor.rb:242:in `synchronize'
/opt/ruby-enterprise-1.8.7-2011.03/lib/ruby/gems/1.8/gems/rake-0.9.2/lib/rake/task.rb:151:in`invoke_with_call_chain'
/opt/ruby-enterprise-1.8.7-2011.03/lib/ruby/gems/1.8/gems/rake-0.9.2/lib/rake/task.rb:176:in `invoke_prerequisites'
/opt/ruby-enterprise-1.8.7-2011.03/lib/ruby/gems/1.8/gems/rake-0.9.2/lib/rake/task.rb:174:in`each'
/opt/ruby-enterprise-1.8.7-2011.03/lib/ruby/gems/1.8/gems/rake-0.9.2/lib/rake/task.rb:174:in `invoke_prerequisites'
/opt/ruby-enterprise-1.8.7-2011.03/lib/ruby/gems/1.8/gems/rake-0.9.2/lib/rake/task.rb:157:in`invoke_with_call_chain'
/opt/ruby-enterprise-1.8.7-2011.03/lib/ruby/1.8/monitor.rb:242:in `synchronize'
/opt/ruby-enterprise-1.8.7-2011.03/lib/ruby/gems/1.8/gems/rake-0.9.2/lib/rake/task.rb:151:in`invoke_with_call_chain'
/opt/ruby-enterprise-1.8.7-2011.03/lib/ruby/gems/1.8/gems/rake-0.9.2/lib/rake/task.rb:144:in `invoke'
/opt/ruby-enterprise-1.8.7-2011.03/lib/ruby/gems/1.8/gems/rake-0.9.2/lib/rake/application.rb:112:in`invoke_task'
/opt/ruby-enterprise-1.8.7-2011.03/lib/ruby/gems/1.8/gems/rake-0.9.2/lib/rake/application.rb:90:in `top_level'
/opt/ruby-enterprise-1.8.7-2011.03/lib/ruby/gems/1.8/gems/rake-0.9.2/lib/rake/application.rb:90:in`each'
/opt/ruby-enterprise-1.8.7-2011.03/lib/ruby/gems/1.8/gems/rake-0.9.2/lib/rake/application.rb:90:in `top_level'
/opt/ruby-enterprise-1.8.7-2011.03/lib/ruby/gems/1.8/gems/rake-0.9.2/lib/rake/application.rb:129:in`standard_exception_handling'
/opt/ruby-enterprise-1.8.7-2011.03/lib/ruby/gems/1.8/gems/rake-0.9.2/lib/rake/application.rb:84:in `top_level'
/opt/ruby-enterprise-1.8.7-2011.03/lib/ruby/gems/1.8/gems/rake-0.9.2/lib/rake/application.rb:62:in`run'
/opt/ruby-enterprise-1.8.7-2011.03/lib/ruby/gems/1.8/gems/rake-0.9.2/lib/rake/application.rb:129:in `standard_exception_handling'
/opt/ruby-enterprise-1.8.7-2011.03/lib/ruby/gems/1.8/gems/rake-0.9.2/lib/rake/application.rb:59:in`run'
/opt/ruby-enterprise-1.8.7-2011.03/lib/ruby/gems/1.8/gems/rake-0.9.2/bin/rake:32
/opt/ruby-enterprise-1.8.7-2011.03/bin/rake:19:in `load'
/opt/ruby-enterprise-1.8.7-2011.03/bin/rake:19
no such file to load -- open-uri-cached
/opt/ruby-enterprise-1.8.7-2011.03/lib/ruby/site_ruby/1.8/rubygems/custom_require.rb:31:in`gem_original_require'
/opt/ruby-enterprise-1.8.7-2011.03/lib/ruby/site_ruby/1.8/rubygems/custom_require.rb:31:in `require'
/opt/ruby-enterprise-1.8.7-2011.03/lib/ruby/gems/1.8/gems/activesupport-2.3.11/lib/active_support/dependencies.rb:184:in`require'
/opt/ruby-enterprise-1.8.7-2011.03/lib/ruby/gems/1.8/gems/rails-2.3.11/lib/rails/gem_dependency.rb:217:in `load'
/opt/ruby-enterprise-1.8.7-2011.03/lib/ruby/gems/1.8/gems/rails-2.3.11/lib/initializer.rb:307:in`load_gems'
/opt/ruby-enterprise-1.8.7-2011.03/lib/ruby/gems/1.8/gems/rails-2.3.11/lib/initializer.rb:307:in `each'
/opt/ruby-enterprise-1.8.7-2011.03/lib/ruby/gems/1.8/gems/rails-2.3.11/lib/initializer.rb:307:in`load_gems'
/opt/ruby-enterprise-1.8.7-2011.03/lib/ruby/gems/1.8/gems/rails-2.3.11/lib/initializer.rb:169:in `process'
/opt/ruby-enterprise-1.8.7-2011.03/lib/ruby/gems/1.8/gems/rails-2.3.11/lib/initializer.rb:113:in`send'
/opt/ruby-enterprise-1.8.7-2011.03/lib/ruby/gems/1.8/gems/rails-2.3.11/lib/initializer.rb:113:in `run'
/home/ubuntu/sites/redmine/releases/20110715095306/config/environment.rb:20
/opt/ruby-enterprise-1.8.7-2011.03/lib/ruby/site_ruby/1.8/rubygems/custom_require.rb:31:in`gem_original_require'
/opt/ruby-enterprise-1.8.7-2011.03/lib/ruby/site_ruby/1.8/rubygems/custom_require.rb:31:in `require'
/opt/ruby-enterprise-1.8.7-2011.03/lib/ruby/gems/1.8/gems/activesupport-2.3.11/lib/active_support/dependencies.rb:182:in`require'
/opt/ruby-enterprise-1.8.7-2011.03/lib/ruby/gems/1.8/gems/activesupport-2.3.11/lib/active_support/dependencies.rb:547:in `new_constants_in'
/opt/ruby-enterprise-1.8.7-2011.03/lib/ruby/gems/1.8/gems/activesupport-2.3.11/lib/active_support/dependencies.rb:182:in`require'
/opt/ruby-enterprise-1.8.7-2011.03/lib/ruby/gems/1.8/gems/rails-2.3.11/lib/tasks/misc.rake:4
/opt/ruby-enterprise-1.8.7-2011.03/lib/ruby/gems/1.8/gems/rake-0.9.2/lib/rake/task.rb:205:in `call'
/opt/ruby-enterprise-1.8.7-2011.03/lib/ruby/gems/1.8/gems/rake-0.9.2/lib/rake/task.rb:205:in`execute'
/opt/ruby-enterprise-1.8.7-2011.03/lib/ruby/gems/1.8/gems/rake-0.9.2/lib/rake/task.rb:200:in `each'
/opt/ruby-enterprise-1.8.7-2011.03/lib/ruby/gems/1.8/gems/rake-0.9.2/lib/rake/task.rb:200:in`execute'
/opt/ruby-enterprise-1.8.7-2011.03/lib/ruby/gems/1.8/gems/rake-0.9.2/lib/rake/task.rb:158:in `invoke_with_call_chain'
/opt/ruby-enterprise-1.8.7-2011.03/lib/ruby/1.8/monitor.rb:242:in`synchronize'
/opt/ruby-enterprise-1.8.7-2011.03/lib/ruby/gems/1.8/gems/rake-0.9.2/lib/rake/task.rb:151:in `invoke_with_call_chain'
/opt/ruby-enterprise-1.8.7-2011.03/lib/ruby/gems/1.8/gems/rake-0.9.2/lib/rake/task.rb:176:in`invoke_prerequisites'
/opt/ruby-enterprise-1.8.7-2011.03/lib/ruby/gems/1.8/gems/rake-0.9.2/lib/rake/task.rb:174:in `each'
/opt/ruby-enterprise-1.8.7-2011.03/lib/ruby/gems/1.8/gems/rake-0.9.2/lib/rake/task.rb:174:in`invoke_prerequisites'
/opt/ruby-enterprise-1.8.7-2011.03/lib/ruby/gems/1.8/gems/rake-0.9.2/lib/rake/task.rb:157:in `invoke_with_call_chain'
/opt/ruby-enterprise-1.8.7-2011.03/lib/ruby/1.8/monitor.rb:242:in`synchronize'
/opt/ruby-enterprise-1.8.7-2011.03/lib/ruby/gems/1.8/gems/rake-0.9.2/lib/rake/task.rb:151:in `invoke_with_call_chain'
/opt/ruby-enterprise-1.8.7-2011.03/lib/ruby/gems/1.8/gems/rake-0.9.2/lib/rake/task.rb:144:in`invoke'
/opt/ruby-enterprise-1.8.7-2011.03/lib/ruby/gems/1.8/gems/rake-0.9.2/lib/rake/application.rb:112:in `invoke_task'
/opt/ruby-enterprise-1.8.7-2011.03/lib/ruby/gems/1.8/gems/rake-0.9.2/lib/rake/application.rb:90:in`top_level'
/opt/ruby-enterprise-1.8.7-2011.03/lib/ruby/gems/1.8/gems/rake-0.9.2/lib/rake/application.rb:90:in `each'
/opt/ruby-enterprise-1.8.7-2011.03/lib/ruby/gems/1.8/gems/rake-0.9.2/lib/rake/application.rb:90:in`top_level'
/opt/ruby-enterprise-1.8.7-2011.03/lib/ruby/gems/1.8/gems/rake-0.9.2/lib/rake/application.rb:129:in `standard_exception_handling'
/opt/ruby-enterprise-1.8.7-2011.03/lib/ruby/gems/1.8/gems/rake-0.9.2/lib/rake/application.rb:84:in`top_level'
/opt/ruby-enterprise-1.8.7-2011.03/lib/ruby/gems/1.8/gems/rake-0.9.2/lib/rake/application.rb:62:in `run'
/opt/ruby-enterprise-1.8.7-2011.03/lib/ruby/gems/1.8/gems/rake-0.9.2/lib/rake/application.rb:129:in`standard_exception_handling'
/opt/ruby-enterprise-1.8.7-2011.03/lib/ruby/gems/1.8/gems/rake-0.9.2/lib/rake/application.rb:59:in `run'
/opt/ruby-enterprise-1.8.7-2011.03/lib/ruby/gems/1.8/gems/rake-0.9.2/bin/rake:32
/opt/ruby-enterprise-1.8.7-2011.03/bin/rake:19:in`load'
/opt/ruby-enterprise-1.8.7-2011.03/bin/rake:19
Missing these required gems:
  open-uri-cached 

You're running:
  ruby 1.8.7.334 at /opt/ruby-enterprise-1.8.7-2011.03/bin/ruby
  rubygems 1.3.7 at /home/ubuntu/.gem/ruby/1.8, /opt/ruby-enterprise-1.8.7-2011.03/lib/ruby/gems/1.8

Run `rake gems:install` to install the missing gems.
..................................................................

I checked all the gems after this error.  All the gems are available on system as per the mentioned location.

So, what is the solution for this ?

Regards,
Omkar

**Comment by ericpaulbishop** [comment] 2011-07-19 15:50
I just tested with redmine 1.2.1, but couldn't reproduce this error.  I am therefore closing this issue.

**Closed as completed by ericpaulbishop** 2011-07-19 15:50 UTC

**Comment by omkar-khutare** [comment] 2011-07-19 16:04
Hi,
Still i have the same issue . Can you please give me the steps for migration of this plugin. I already referred the steps from mentioned docs with this plugin.

Regards,
Omkar

**Comment by ericpaulbishop** [comment] 2011-07-19 16:14
First, before worrying about the plugin, are you sure that redmine is
installed properly?  Do you have it behaving properly?  Looking at the
trace it doesn't look like any code in the plugin is generating your
error, on top of which I cannot reproduce it.  It sounds like your
problem may not be with the plugin itself.

Eric

On Tue, Jul 19, 2011 at 12:04 PM, omkar-khutare
reply@reply.github.com
wrote:

**Comment by omkar-khutare** [comment] 2011-07-22 07:19
Hey Eric,

Solved the issue . My redmine was not configured properly.

Omkar
